from pathlib import Path
from .policy_store import load_policy

# โฟลเดอร์ฐานของโปรเจกต์ (ที่มี policy.json, secret.env)
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_ENV_PATH = BASE_DIR / "secret.env"


def load_shared_key() -> str:
    """
    อ่านค่า TACACS_SHARED_KEY จาก secret.env
    ถ้าไม่เจอหรือไม่มีให้ใช้ค่า CHANGE_ME เป็นค่าเตือน
    """
    if not SECRET_ENV_PATH.exists():
        return "CHANGE_ME"

    for line in SECRET_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("TACACS_SHARED_KEY="):
            return line.split("=", 1)[1].strip()

    return "CHANGE_ME"


def build_config_text() -> str:
    policy = load_policy()
    users   = policy.get("users", [])
    roles   = policy.get("roles", [])
    devices = policy.get("devices", [])

    shared_key = load_shared_key()

    lines: list[str] = []

    lines.append("# Auto-generated by NT TACACS+ Dashboard")
    lines.append("# ห้ามแก้ไฟล์นี้ตรง ๆ (จะแทนที่ทุกครั้งที่ generate จาก web)")
    lines.append("")

    # ---------- spawnd ----------
    lines.append("id = spawnd {")
    lines.append("  listen = {")
    lines.append("    port = 49")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # ---------- tac_plus-ng ----------
    lines.append("id = tac_plus-ng {")
    lines.append("  # Devices (map จาก policy.devices -> host)")
    for dev in devices:
        name = dev.get("name") or dev.get("id") or "OLT_UNKNOWN"
        addr = dev.get("address") or dev.get("ip") or "0.0.0.0"
        lines.append(f"  host = {name} {{")
        lines.append(f"    address = {addr}")
        # ใช้ shared_key จาก secret.env (ใส่ใน "" เผื่อมีตัวพิเศษ)
        lines.append(f'    key = "{shared_key}"')
        lines.append("  }")
        lines.append("")

    lines.append("  # Roles (as groups)")
    for r in roles:
        name = r.get("name") or "ROLE_NO_NAME"
        desc = r.get("description") or ""
        priv = r.get("privilege") or ""
        lines.append(f"  group = {name} {{")
        if priv:
            lines.append(f"    # privilege: {priv}")
        if desc:
            lines.append(f"    # description: {desc}")
        lines.append("  }")
        lines.append("")

    lines.append("  # Users")
    for u in users:
        username = u.get("username") or "user_unknown"
        role     = u.get("role") or u.get("roles") or ""
        lines.append(f"  user = {username} {{")
        lines.append("    # login = clear <ใส่รหัสจริง หรือใช้ backend อื่น>")
        if role:
            lines.append(f"    member = {role}")
        lines.append("  }")
        lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)

