from pathlib import Path
import re

from .policy_store import load_policy

# โฟลเดอร์ฐานของโปรเจกต์ (ที่มี policy.json, secret.env, pass.secret)
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_ENV_PATH = BASE_DIR / "secret.env"
PASS_SECRET_PATH = BASE_DIR / "pass.secret"


def load_shared_key() -> str:
    """อ่านค่า TACACS_SHARED_KEY จาก secret.env"""
    if not SECRET_ENV_PATH.exists():
        return "CHANGE_ME"

    for line in SECRET_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("TACACS_SHARED_KEY="):
            return line.split("=", 1)[1].strip()

    return "CHANGE_ME"


def load_default_user_password() -> str:
    """อ่าน DEFAULT_USER_PASSWORD จาก secret.env (ถ้าไม่มีก็ใช้ test)"""
    if not SECRET_ENV_PATH.exists():
        return "test"

    for line in SECRET_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("DEFAULT_USER_PASSWORD="):
            return line.split("=", 1)[1].strip() or "test"

    return "test"


def _escape(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def _parse_privilege(value) -> int:
    """
    role.privilege ในเว็บอาจเป็น '15' หรือ '15 / full' -> เอาเลขตัวแรก
    ถ้าไม่เจอให้ default เป็น 1 (อย่าเป็น 0)
    """
    if value is None:
        return 1
    m = re.search(r"\d+", str(value))
    return int(m.group(0)) if m else 1


def build_config_text() -> str:
    """สร้าง tacacs-generated.cfg"""
    policy = load_policy()
    roles = policy.get("roles", [])
    devices = policy.get("devices", [])
    shared_key = load_shared_key()

    lines: list[str] = []
    lines.append("# Auto-generated by NT TACACS+ Dashboard")
    lines.append("# ห้ามแก้ไฟล์นี้ตรง ๆ (จะแทนที่ทุกครั้งที่ generate จาก web)")
    lines.append("")

    # spawnd
    lines.append("id = spawnd {")
    lines.append("  listen = {")
    lines.append("    port = 49")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # tac_plus-ng
    lines.append("id = tac_plus-ng {")
    lines.append("  # Devices (map จาก policy.devices -> host)")
    for dev in devices:
        name = dev.get("name") or dev.get("id") or "OLT_UNKNOWN"
        addr = dev.get("address") or dev.get("ip") or "0.0.0.0"
        lines.append(f"  host = {name} {{")
        lines.append(f"    address = {addr}")
        lines.append(f'    key = "{_escape(shared_key)}"')
        lines.append("  }")
        lines.append("")

    lines.append("  # Roles (as groups)")
    for r in roles:
        name = r.get("name") or "ROLE_NO_NAME"
        desc = r.get("description") or ""
        priv = r.get("privilege")
        lines.append(f"  group = {name} {{")
        if priv is not None:
            lines.append(f"    # privilege: {priv}")
        if desc:
            lines.append(f"    # description: {desc}")
        lines.append("  }")
        lines.append("")

    # include pass.secret
    lines.append("  # Users are defined in separate pass.secret file")
    lines.append(f'  include = "{PASS_SECRET_PATH}"')
    lines.append("}")

    return "\n".join(lines)


def build_pass_secret_text() -> str:
    policy = load_policy()
    users = policy.get("users", [])
    roles = policy.get("roles", [])

    role_priv = {r.get("name"): _parse_privilege(r.get("privilege")) for r in roles}
    default_pw = load_default_user_password()

    lines: list[str] = []
    lines.append("# Auto-generated by NT TACACS+ Dashboard")
    lines.append("# ห้ามแก้ไฟล์นี้ตรง ๆ (จะแทนที่ทุกครั้งที่ generate จาก web)")
    lines.append("")

    for u in users:
        username = (u.get("username") or u.get("name") or "").strip()
        if not username:
            continue

        status = (u.get("status") or "Active").strip().lower()
        if status not in ("active", "enable", "enabled"):
            continue

        role = (
            u.get("roles")
            or u.get("group")
            or u.get("role_name")
            or u.get("roleName")
            or "OLT_VIEW"
        )
        role = str(role).strip()

        priv = role_priv.get(role, 1)
        priv = max(1, min(15, priv))
        pw = u.get("password") or default_pw

        lines.append(f"user {username} {{")
        lines.append(f'  password login = clear "{_escape(pw)}"')
        lines.append("  password pap = login")
        lines.append(f"  member = {role}")
        lines.append("")
        lines.append("  profile {")
        lines.append("    script {")
        lines.append("      if (service == shell) {")
        lines.append(f"        set priv-lvl = {priv}")
        lines.append("        permit")
        lines.append("      }")
        lines.append("      permit")
        lines.append("    }")
        lines.append("  }")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)

