# tacacs_dashboard/services/tacacs_config.py
from pathlib import Path
import re

from .policy_store import load_policy

BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_ENV_PATH = BASE_DIR / "secret.env"
PASS_SECRET_PATH = BASE_DIR / "pass.secret"


def load_shared_key() -> str:
    if not SECRET_ENV_PATH.exists():
        return "CHANGE_ME"
    for line in SECRET_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("TACACS_SHARED_KEY="):
            return line.split("=", 1)[1].strip()
    return "CHANGE_ME"


def load_default_user_password() -> str:
    if not SECRET_ENV_PATH.exists():
        return "test"
    for line in SECRET_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("DEFAULT_USER_PASSWORD="):
            return line.split("=", 1)[1].strip() or "test"
    return "test"


def _escape(s: str) -> str:
    return (s or "").replace("\\", "\\\\").replace('"', '\\"')


def _parse_privilege(value) -> int:
    """
    policy roles[].privilege อาจเป็น '15', 15, หรือ '15 / full'
    """
    if value is None:
        return 1
    m = re.search(r"\d+", str(value))
    return int(m.group(0)) if m else 1


def _role_mode(role_name: str) -> str:
    n = (role_name or "").upper()
    if "ADMIN" in n:
        return "ADMIN"
    if "ENGINEER" in n:
        return "ENGINEER"
    return "VIEW"


def build_config_text() -> str:
    policy = load_policy()
    roles = policy.get("roles", [])
    devices = policy.get("devices", [])
    shared_key = load_shared_key()

    lines: list[str] = []
    lines.append("# Auto-generated by NT TACACS+ Dashboard")
    lines.append("# ห้ามแก้ไฟล์นี้ตรง ๆ (จะแทนที่ทุกครั้งที่ generate จาก web)")
    lines.append("")

    # spawnd
    lines.append("id = spawnd {")
    lines.append("  listen = {")
    lines.append("    port = 49")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # tac_plus-ng
    lines.append("id = tac_plus-ng {")
    lines.append("  # ----- Logging (authc/authz/acct/conn) -----")
    lines.append("  log authclog { destination = /var/log/tac_plus/authc-%Y-%m-%d.log }")
    lines.append("  log authzlog { destination = /var/log/tac_plus/authz-%Y-%m-%d.log }")
    lines.append("  log acctlog  { destination = /var/log/tac_plus/acct-%Y-%m-%d.log }")
    lines.append("  log connlog  { destination = /var/log/tac_plus/conn-%Y-%m-%d.log }")
    lines.append("")
    lines.append("  authentication log = authclog")
    lines.append("  authorization log = authzlog")
    lines.append("  accounting log = acctlog")
    lines.append("  connection log = connlog")
    lines.append("")

    # Devices
    lines.append("  # Devices (map จาก policy.devices -> host)")
    for dev in devices:
        name = dev.get("name") or dev.get("id") or "OLT_UNKNOWN"
        addr = dev.get("address") or dev.get("ip") or "0.0.0.0"
        lines.append(f"  host = {name} {{")
        lines.append(f"    address = {addr}")
        lines.append(f'    key = "{_escape(shared_key)}"')
        lines.append("  }")
        lines.append("")

    # Roles -> groups + profile(script)  (<<< จุดสำคัญของแนวทาง B อยู่ตรงนี้)
    lines.append("  # Roles (as groups) + RBAC policy (command authorization)")
    for r in roles:
        name = (r.get("name") or "ROLE_NO_NAME").strip()
        desc = (r.get("description") or "").strip()
        priv_raw = r.get("privilege")
        priv = _parse_privilege(priv_raw)
        priv = max(1, min(15, priv))
        mode = _role_mode(name)

        lines.append(f"  group = {name} {{")
        if priv_raw is not None:
            lines.append(f"    # privilege: {priv_raw}")
        if desc:
            lines.append(f"    # description: {desc}")

        lines.append("    profile {")
        lines.append("      script {")
        lines.append("        if (service == shell) {")
        lines.append(f'          if (cmd == "") {{ set priv-lvl = {priv}; permit }}')

        if mode == "VIEW":
            # allow only show/exit/logout
            lines.append(r'          if (cmd =~ "^(show|exit|logout)(\s|$)") { permit }')
            lines.append("          deny")
        elif mode == "ENGINEER":
            # deny conf t / configure
            lines.append(r'          if (cmd =~ "^(conf|configure)(\s|$)") { deny }')
            lines.append("          permit")
        else:
            # ADMIN
            lines.append("          permit")

        lines.append("        }")
        lines.append("        permit")
        lines.append("      }")
        lines.append("    }")
        lines.append("  }")
        lines.append("")

    # include users
    lines.append("  # Users are defined in separate pass.secret file")
    lines.append(f'  include = "{PASS_SECRET_PATH}"')
    lines.append("}")

    return "\n".join(lines)


def build_pass_secret_text() -> str:
    """
    pass.secret ให้เหลือแค่ user + member(role)
    RBAC policy ไปอยู่ใน group profile ของ tacacs-generated.cfg
    """
    policy = load_policy()
    users = policy.get("users", [])
    default_pw = load_default_user_password()

    lines: list[str] = []
    lines.append("# Auto-generated by NT TACACS+ Dashboard")
    lines.append("# ห้ามแก้ไฟล์นี้ตรง ๆ (จะแทนที่ทุกครั้งที่ generate จาก web)")
    lines.append("")

    for u in users:
        username = (u.get("username") or u.get("name") or "").strip()
        if not username:
            continue

        status = (u.get("status") or "Active").strip().lower()
        if status not in ("active", "enable", "enabled"):
            continue

        # policy.json ของคุณใช้ key = roles (string)
        role = (
            u.get("roles")
            or u.get("group")
            or u.get("role")
            or "OLT_VIEW"
        )
        role = str(role).strip()

        pw = u.get("password") or default_pw

        lines.append(f"user {username} {{")
        lines.append(f'  password login = clear "{_escape(pw)}"')
        lines.append("  password pap = login")
        lines.append(f"  member = {role}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)

